// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qeelyn/protobuf/date.proto

package date // import "github.com/qeelyn/go-common/protobuf/date"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Date struct {
	// Year of date. Must be from 1 to 9999, or 0 if specifying a date without
	// a year.
	Year int32 `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	// Month of year. Must be from 1 to 12.
	Month int32 `protobuf:"varint,2,opt,name=month" json:"month,omitempty"`
	// Day of month. Must be from 1 to 31 and valid for the year and month, or 0
	// if specifying a year/month where the day is not significant.
	Day                  int32    `protobuf:"varint,3,opt,name=day" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_date_ed014211905deebc, []int{0}
}
func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (dst *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(dst, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func init() {
	proto.RegisterType((*Date)(nil), "qeelyn.protobuf.Date")
}

func init() { proto.RegisterFile("qeelyn/protobuf/date.proto", fileDescriptor_date_ed014211905deebc) }

var fileDescriptor_date_ed014211905deebc = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x4c, 0x4d, 0xcd,
	0xa9, 0xcc, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0x49, 0x2c, 0x49,
	0xd5, 0x03, 0xf3, 0x84, 0xf8, 0x21, 0x72, 0x7a, 0x30, 0x39, 0x25, 0x27, 0x2e, 0x16, 0x97, 0xc4,
	0x92, 0x54, 0x21, 0x21, 0x2e, 0x96, 0xca, 0xd4, 0xc4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6,
	0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x35, 0x37, 0x3f, 0xaf, 0x24, 0x43, 0x82, 0x09, 0x2c, 0x08,
	0xe1, 0x08, 0x09, 0x70, 0x31, 0xa7, 0x24, 0x56, 0x4a, 0x30, 0x83, 0xc5, 0x40, 0x4c, 0x27, 0xed,
	0x28, 0xcd, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0xa8, 0xed, 0xe9,
	0xf9, 0xba, 0xc9, 0xf9, 0xb9, 0xb9, 0xf9, 0x68, 0xee, 0x48, 0x62, 0x03, 0x73, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xd7, 0xe4, 0x44, 0x80, 0xa6, 0x00, 0x00, 0x00,
}
