// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qeelyn/protobuf/pageinfo.proto

package paginate // import "github.com/qeelyn/go-common/protobuf/paginate"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PageInfo struct {
	StartCursor          string   `protobuf:"bytes,1,opt,name=startCursor" json:"startCursor,omitempty"`
	EndCursor            string   `protobuf:"bytes,2,opt,name=endCursor" json:"endCursor,omitempty"`
	HasNextPage          bool     `protobuf:"varint,3,opt,name=hasNextPage" json:"hasNextPage,omitempty"`
	HasPreviousPage      bool     `protobuf:"varint,4,opt,name=hasPreviousPage" json:"hasPreviousPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pageinfo_1b33516d9b8dabaa, []int{0}
}
func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (dst *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(dst, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetStartCursor() string {
	if m != nil {
		return m.StartCursor
	}
	return ""
}

func (m *PageInfo) GetEndCursor() string {
	if m != nil {
		return m.EndCursor
	}
	return ""
}

func (m *PageInfo) GetHasNextPage() bool {
	if m != nil {
		return m.HasNextPage
	}
	return false
}

func (m *PageInfo) GetHasPreviousPage() bool {
	if m != nil {
		return m.HasPreviousPage
	}
	return false
}

func init() {
	proto.RegisterType((*PageInfo)(nil), "qeelyn.protobuf.PageInfo")
}

func init() {
	proto.RegisterFile("qeelyn/protobuf/pageinfo.proto", fileDescriptor_pageinfo_1b33516d9b8dabaa)
}

var fileDescriptor_pageinfo_1b33516d9b8dabaa = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x4c, 0x4d, 0xcd,
	0xa9, 0xcc, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x48, 0x4c, 0x4f,
	0xcd, 0xcc, 0x4b, 0xcb, 0xd7, 0x03, 0x8b, 0x08, 0xf1, 0x43, 0xe4, 0xf5, 0x60, 0xf2, 0x4a, 0xd3,
	0x18, 0xb9, 0x38, 0x02, 0x12, 0xd3, 0x53, 0x3d, 0xf3, 0xd2, 0xf2, 0x85, 0x14, 0xb8, 0xb8, 0x8b,
	0x4b, 0x12, 0x8b, 0x4a, 0x9c, 0x4b, 0x8b, 0x8a, 0xf3, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x90, 0x85, 0x84, 0x64, 0xb8, 0x38, 0x53, 0xf3, 0x52, 0xa0, 0xf2, 0x4c, 0x60, 0x79, 0x84,
	0x00, 0x48, 0x7f, 0x46, 0x62, 0xb1, 0x5f, 0x6a, 0x45, 0x09, 0xc8, 0x48, 0x09, 0x66, 0x05, 0x46,
	0x0d, 0x8e, 0x20, 0x64, 0x21, 0x21, 0x0d, 0x2e, 0xfe, 0x8c, 0xc4, 0xe2, 0x80, 0xa2, 0xd4, 0xb2,
	0xcc, 0xfc, 0xd2, 0x62, 0xb0, 0x2a, 0x16, 0xb0, 0x2a, 0x74, 0x61, 0x27, 0xfd, 0x28, 0xdd, 0xf4,
	0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0xa8, 0xb7, 0xd2, 0xf3, 0x75, 0x93,
	0xf3, 0x73, 0x73, 0xf3, 0x51, 0x3d, 0x98, 0x99, 0x97, 0x58, 0x92, 0x9a, 0xc4, 0x06, 0x16, 0x32,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x4d, 0x91, 0x49, 0x03, 0x01, 0x00, 0x00,
}
