// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/paginate/paginate.proto

package paginate // import "github.com/qeelyn/go-common/protobuf/paginate"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Paginate struct {
	StartCursor          string   `protobuf:"bytes,1,opt,name=startCursor" json:"startCursor,omitempty"`
	EndCursor            string   `protobuf:"bytes,2,opt,name=endCursor" json:"endCursor,omitempty"`
	HasNextPage          bool     `protobuf:"varint,3,opt,name=hasNextPage" json:"hasNextPage,omitempty"`
	HasPreviousPage      bool     `protobuf:"varint,4,opt,name=hasPreviousPage" json:"hasPreviousPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paginate) Reset()         { *m = Paginate{} }
func (m *Paginate) String() string { return proto.CompactTextString(m) }
func (*Paginate) ProtoMessage()    {}
func (*Paginate) Descriptor() ([]byte, []int) {
	return fileDescriptor_paginate_b3723201b87ef71c, []int{0}
}
func (m *Paginate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paginate.Unmarshal(m, b)
}
func (m *Paginate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paginate.Marshal(b, m, deterministic)
}
func (dst *Paginate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paginate.Merge(dst, src)
}
func (m *Paginate) XXX_Size() int {
	return xxx_messageInfo_Paginate.Size(m)
}
func (m *Paginate) XXX_DiscardUnknown() {
	xxx_messageInfo_Paginate.DiscardUnknown(m)
}

var xxx_messageInfo_Paginate proto.InternalMessageInfo

func (m *Paginate) GetStartCursor() string {
	if m != nil {
		return m.StartCursor
	}
	return ""
}

func (m *Paginate) GetEndCursor() string {
	if m != nil {
		return m.EndCursor
	}
	return ""
}

func (m *Paginate) GetHasNextPage() bool {
	if m != nil {
		return m.HasNextPage
	}
	return false
}

func (m *Paginate) GetHasPreviousPage() bool {
	if m != nil {
		return m.HasPreviousPage
	}
	return false
}

func init() {
	proto.RegisterType((*Paginate)(nil), "qeelyn.protobuf.Paginate")
}

func init() {
	proto.RegisterFile("protobuf/paginate/paginate.proto", fileDescriptor_paginate_b3723201b87ef71c)
}

var fileDescriptor_paginate_b3723201b87ef71c = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x48, 0x4c, 0xcf, 0xcc, 0x4b, 0x2c, 0x49, 0x85, 0x33, 0xf4,
	0xc0, 0x52, 0x42, 0xfc, 0x85, 0xa9, 0xa9, 0x39, 0x95, 0x79, 0x7a, 0x30, 0x85, 0x4a, 0xd3, 0x18,
	0xb9, 0x38, 0x02, 0xa0, 0x6a, 0x84, 0x14, 0xb8, 0xb8, 0x8b, 0x4b, 0x12, 0x8b, 0x4a, 0x9c, 0x4b,
	0x8b, 0x8a, 0xf3, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x85, 0x84, 0x64, 0xb8,
	0x38, 0x53, 0xf3, 0x52, 0xa0, 0xf2, 0x4c, 0x60, 0x79, 0x84, 0x00, 0x48, 0x7f, 0x46, 0x62, 0xb1,
	0x5f, 0x6a, 0x45, 0x49, 0x40, 0x62, 0x7a, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x47, 0x10, 0xb2,
	0x90, 0x90, 0x06, 0x17, 0x7f, 0x46, 0x62, 0x71, 0x40, 0x51, 0x6a, 0x59, 0x66, 0x7e, 0x69, 0x31,
	0x58, 0x15, 0x0b, 0x58, 0x15, 0xba, 0xb0, 0x93, 0x7e, 0x94, 0x6e, 0x7a, 0x66, 0x49, 0x46, 0x69,
	0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0xc4, 0xd9, 0xfa, 0xe9, 0xf9, 0xba, 0xc9, 0xf9, 0xb9, 0xb9,
	0xf9, 0x79, 0xfa, 0x18, 0x3e, 0x4d, 0x62, 0x03, 0x0b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x18, 0xab, 0xc1, 0x0d, 0x05, 0x01, 0x00, 0x00,
}
