// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/paginate/paginate.proto

package paginate // import "github.com/qeelyn/go-common/protobuf/paginate"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Paginate struct {
	First                int32    `protobuf:"varint,1,opt,name=first" json:"first,omitempty"`
	After                string   `protobuf:"bytes,2,opt,name=after" json:"after,omitempty"`
	Last                 int32    `protobuf:"varint,3,opt,name=last" json:"last,omitempty"`
	Before               string   `protobuf:"bytes,4,opt,name=before" json:"before,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paginate) Reset()         { *m = Paginate{} }
func (m *Paginate) String() string { return proto.CompactTextString(m) }
func (*Paginate) ProtoMessage()    {}
func (*Paginate) Descriptor() ([]byte, []int) {
	return fileDescriptor_paginate_ad67c31d671a9b68, []int{0}
}
func (m *Paginate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paginate.Unmarshal(m, b)
}
func (m *Paginate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paginate.Marshal(b, m, deterministic)
}
func (dst *Paginate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paginate.Merge(dst, src)
}
func (m *Paginate) XXX_Size() int {
	return xxx_messageInfo_Paginate.Size(m)
}
func (m *Paginate) XXX_DiscardUnknown() {
	xxx_messageInfo_Paginate.DiscardUnknown(m)
}

var xxx_messageInfo_Paginate proto.InternalMessageInfo

func (m *Paginate) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *Paginate) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *Paginate) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *Paginate) GetBefore() string {
	if m != nil {
		return m.Before
	}
	return ""
}

func init() {
	proto.RegisterType((*Paginate)(nil), "qeelyn.protobuf.Paginate")
}

func init() {
	proto.RegisterFile("qeelyn/protobuf/paginate.proto", fileDescriptor_paginate_ad67c31d671a9b68)
}

var fileDescriptor_paginate_ad67c31d671a9b68 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x48, 0x4c, 0xcf, 0xcc, 0x4b, 0x2c, 0x49, 0x85, 0x33, 0xf4,
	0xc0, 0x52, 0x42, 0xfc, 0x85, 0xa9, 0xa9, 0x39, 0x95, 0x79, 0x7a, 0x30, 0x85, 0x4a, 0x49, 0x5c,
	0x1c, 0x01, 0x50, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x69, 0x99, 0x45, 0xc5, 0x25, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0xac, 0x41, 0x10, 0x0e, 0x48, 0x34, 0x31, 0xad, 0x24, 0xb5, 0x48, 0x82, 0x49, 0x81,
	0x51, 0x83, 0x33, 0x08, 0xc2, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x49, 0x2c, 0x2e, 0x91, 0x60, 0x06,
	0x2b, 0x05, 0xb3, 0x85, 0xc4, 0xb8, 0xd8, 0x92, 0x52, 0xd3, 0xf2, 0x8b, 0x52, 0x25, 0x58, 0xc0,
	0x4a, 0xa1, 0x3c, 0x27, 0xfd, 0x28, 0xdd, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc,
	0x5c, 0x7d, 0x88, 0x0b, 0xf4, 0xd3, 0xf3, 0x75, 0x93, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0xf4, 0x31,
	0x1c, 0x9d, 0xc4, 0x06, 0x16, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x21, 0xfc, 0x57, 0x78,
	0xd0, 0x00, 0x00, 0x00,
}
