// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qeelyn/protobuf/pagination.proto

package paginate // import "github.com/qeelyn/go-common/protobuf/paginate"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pagination struct {
	First                int32    `protobuf:"varint,1,opt,name=first" json:"first,omitempty"`
	After                string   `protobuf:"bytes,2,opt,name=after" json:"after,omitempty"`
	Last                 int32    `protobuf:"varint,3,opt,name=last" json:"last,omitempty"`
	Before               string   `protobuf:"bytes,4,opt,name=before" json:"before,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_pagination_ae0bb8c82cec19b9, []int{0}
}
func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (dst *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(dst, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *Pagination) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *Pagination) GetLast() int32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *Pagination) GetBefore() string {
	if m != nil {
		return m.Before
	}
	return ""
}

func init() {
	proto.RegisterType((*Pagination)(nil), "qeelyn.protobuf.Pagination")
}

func init() {
	proto.RegisterFile("qeelyn/protobuf/pagination.proto", fileDescriptor_pagination_ae0bb8c82cec19b9)
}

var fileDescriptor_pagination_ae0bb8c82cec19b9 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x4c, 0x4d, 0xcd,
	0xa9, 0xcc, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x48, 0x4c, 0xcf,
	0xcc, 0x4b, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x8b, 0x09, 0xf1, 0x43, 0x54, 0xe8, 0xc1, 0x54,
	0x28, 0xa5, 0x70, 0x71, 0x05, 0xc0, 0x15, 0x09, 0x89, 0x70, 0xb1, 0xa6, 0x65, 0x16, 0x15, 0x97,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x38, 0x20, 0xd1, 0xc4, 0xb4, 0x92, 0xd4, 0x22,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x88, 0x8b, 0x25, 0x27, 0xb1, 0xb8,
	0x44, 0x82, 0x19, 0xac, 0x14, 0xcc, 0x16, 0x12, 0xe3, 0x62, 0x4b, 0x4a, 0x4d, 0xcb, 0x2f, 0x4a,
	0x95, 0x60, 0x01, 0x2b, 0x85, 0xf2, 0x9c, 0xf4, 0xa3, 0x74, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93,
	0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xa1, 0xae, 0x4c, 0xcf, 0xd7, 0x4d, 0xce, 0xcf, 0xcd, 0xcd, 0xc7,
	0x74, 0x6f, 0x6a, 0x12, 0x1b, 0x58, 0xc8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xb9, 0x05,
	0xaa, 0xd2, 0x00, 0x00, 0x00,
}
